### ISSUE TITLE
小幅度滚动，出现滚动回弹

### ISSUE THREAD

**Issue by sinlazhan** [yuruiyin/AppbarLayoutBehavior#3]
部分机型，小幅度向上或向下，偶尔会出现短距离回弹，大佬能看下吗

**Comment by yuruiyin** [comment]
> 部分机型，小幅度向上或向下，偶尔会出现短距离回弹，大佬能看下吗

什么机型？

**Comment by yuruiyin** [comment]
> 部分机型，小幅度向上或向下，偶尔会出现短距离回弹，大佬能看下吗

@sinlazhan 什么机型

**Comment by sinlazhan** [comment]
@yuruiyin  vivo x21 华为荣耀9等

**Comment by sinlazhan** [comment]
> > 部分机型，小幅度向上或向下，偶尔会出现短距离回弹，大佬能看下吗
> 
> @sinlazhan 什么机型
